# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yh/ExtendibleRadixTree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yh/ExtendibleRadixTree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yh/ExtendibleRadixTree/CMakeFiles /home/yh/ExtendibleRadixTree//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yh/ExtendibleRadixTree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nvmkv

# Build rule for target.
nvmkv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv
.PHONY : nvmkv

# fast build rule for target.
nvmkv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvmkv.dir/build.make CMakeFiles/nvmkv.dir/build
.PHONY : nvmkv/fast

#=============================================================================
# Target rules for targets named nvmkv-ert

# Build rule for target.
nvmkv-ert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-ert
.PHONY : nvmkv-ert

# fast build rule for target.
nvmkv-ert/fast:
	$(MAKE) $(MAKESILENT) -f ert/CMakeFiles/nvmkv-ert.dir/build.make ert/CMakeFiles/nvmkv-ert.dir/build
.PHONY : nvmkv-ert/fast

#=============================================================================
# Target rules for targets named nvmkv-fastalloc

# Build rule for target.
nvmkv-fastalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-fastalloc
.PHONY : nvmkv-fastalloc

# fast build rule for target.
nvmkv-fastalloc/fast:
	$(MAKE) $(MAKESILENT) -f fastalloc/CMakeFiles/nvmkv-fastalloc.dir/build.make fastalloc/CMakeFiles/nvmkv-fastalloc.dir/build
.PHONY : nvmkv-fastalloc/fast

#=============================================================================
# Target rules for targets named nvmkv-rng

# Build rule for target.
nvmkv-rng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-rng
.PHONY : nvmkv-rng

# fast build rule for target.
nvmkv-rng/fast:
	$(MAKE) $(MAKESILENT) -f rng/CMakeFiles/nvmkv-rng.dir/build.make rng/CMakeFiles/nvmkv-rng.dir/build
.PHONY : nvmkv-rng/fast

#=============================================================================
# Target rules for targets named nvmkv-roert

# Build rule for target.
nvmkv-roert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-roert
.PHONY : nvmkv-roert

# fast build rule for target.
nvmkv-roert/fast:
	$(MAKE) $(MAKESILENT) -f roert/CMakeFiles/nvmkv-roert.dir/build.make roert/CMakeFiles/nvmkv-roert.dir/build
.PHONY : nvmkv-roert/fast

#=============================================================================
# Target rules for targets named nvmkv-fastfair

# Build rule for target.
nvmkv-fastfair: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-fastfair
.PHONY : nvmkv-fastfair

# fast build rule for target.
nvmkv-fastfair/fast:
	$(MAKE) $(MAKESILENT) -f fastfair/CMakeFiles/nvmkv-fastfair.dir/build.make fastfair/CMakeFiles/nvmkv-fastfair.dir/build
.PHONY : nvmkv-fastfair/fast

#=============================================================================
# Target rules for targets named nvmkv-lbt

# Build rule for target.
nvmkv-lbt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-lbt
.PHONY : nvmkv-lbt

# fast build rule for target.
nvmkv-lbt/fast:
	$(MAKE) $(MAKESILENT) -f lbtree/CMakeFiles/nvmkv-lbt.dir/build.make lbtree/CMakeFiles/nvmkv-lbt.dir/build
.PHONY : nvmkv-lbt/fast

#=============================================================================
# Target rules for targets named nvmkv-wort

# Build rule for target.
nvmkv-wort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-wort
.PHONY : nvmkv-wort

# fast build rule for target.
nvmkv-wort/fast:
	$(MAKE) $(MAKESILENT) -f wort/CMakeFiles/nvmkv-wort.dir/build.make wort/CMakeFiles/nvmkv-wort.dir/build
.PHONY : nvmkv-wort/fast

#=============================================================================
# Target rules for targets named nvmkv-woart

# Build rule for target.
nvmkv-woart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-woart
.PHONY : nvmkv-woart

# fast build rule for target.
nvmkv-woart/fast:
	$(MAKE) $(MAKESILENT) -f woart/CMakeFiles/nvmkv-woart.dir/build.make woart/CMakeFiles/nvmkv-woart.dir/build
.PHONY : nvmkv-woart/fast

#=============================================================================
# Target rules for targets named nvmkv-roart

# Build rule for target.
nvmkv-roart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvmkv-roart
.PHONY : nvmkv-roart

# fast build rule for target.
nvmkv-roart/fast:
	$(MAKE) $(MAKESILENT) -f roart/CMakeFiles/nvmkv-roart.dir/build.make roart/CMakeFiles/nvmkv-roart.dir/build
.PHONY : nvmkv-roart/fast

db_bench.o: db_bench.cpp.o
.PHONY : db_bench.o

# target to build an object file
db_bench.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvmkv.dir/build.make CMakeFiles/nvmkv.dir/db_bench.cpp.o
.PHONY : db_bench.cpp.o

db_bench.i: db_bench.cpp.i
.PHONY : db_bench.i

# target to preprocess a source file
db_bench.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvmkv.dir/build.make CMakeFiles/nvmkv.dir/db_bench.cpp.i
.PHONY : db_bench.cpp.i

db_bench.s: db_bench.cpp.s
.PHONY : db_bench.s

# target to generate assembly for a file
db_bench.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvmkv.dir/build.make CMakeFiles/nvmkv.dir/db_bench.cpp.s
.PHONY : db_bench.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nvmkv"
	@echo "... nvmkv-ert"
	@echo "... nvmkv-fastalloc"
	@echo "... nvmkv-fastfair"
	@echo "... nvmkv-lbt"
	@echo "... nvmkv-rng"
	@echo "... nvmkv-roart"
	@echo "... nvmkv-roert"
	@echo "... nvmkv-woart"
	@echo "... nvmkv-wort"
	@echo "... db_bench.o"
	@echo "... db_bench.i"
	@echo "... db_bench.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

